name: simple-social-network-2
app_id: da_KN4IZtyUg3OE
owner: aadityaparashar0901
package: '.'
volumes:
- name: simple-social-network-2_posts
  mount: /app/posts
scaling:
  mode: single_concurrency
kind: wasmer.io/App.v0
